---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm i -g vuepress
      - vuepress build
  
  - name: release
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      repo: registry.ubu-002.km8.es/into-phoenix
      registry: registry.ubu-002.km8.es
      username:
        from_secret: docker_repo_user
      password:
        from_secret: docker_repo_password

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: web-01.km8.es
      port: 22
      username:
        from_secret: web-01_ssh_user
      key:
        from_secret: web-01_ssh_key
      passphrase:
        from_secret: web-01_ssh_passphrase
      script:
        - cd /srv/docker/into-phoenix
        - docker-compose down
        - docker-compose pull
        - docker-compose up -d