name: Production build
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: KeenMate/gha-shared/.github/workflows/deploy-docker-image.yml@master
    secrets: inherit
    with:
      image-name: into-phoenix
      deployment-host: web-01.km8.vm
      deployment-dir: into-phoenix